# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://app.vagrantup.com/centos/boxes/7"
  config.vm.define  "testbox-pulp"
  config.vm.hostname = "testbox-pulp"
  
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", inline: <<-SHELL
    sudo setenforce 0 
    sudo yum install -y epel-release
    sudo yum install -y ansible
    sudo yum install -y tig
    sudo yum install -y python-pip
    sudo pip install ansible==2.6.17
    # Add this host to default ansible inventory
    sudo sh -c 'echo $HOSTNAME > /etc/ansible/hosts'
    sudo mkdir /root/.ssh
    sudo chmod 700 /root/.ssh
    sudo echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAgDujOojyhkm8tRvrAkPBLtsCAUAXoq+CeGlR84/2/xJwl5x9/sWLegvXHIMjST45PmDmuZC+qo59NcAmyCHr6hCmsskyjtiXmZgnPmIzelGojYLK6ScHB2ZcarbcQND7W3+BqGyzwZJPPjU3LBKCUAdJ767sQKifnAGZSMMTW9HlNnzHJQPrTzwXRo5S2JqVICwzPb/4wI+LROxpO5r8R+/f81BtXMRorkzgwC7SYxVziwS+/j4yMNr8TE7DNAsL88cTB5GgD39p6j0nlWK7DvIctX+clEZhhFpB9oKUVHG/Ms1FTetRlUOTay6pu7vfbgXlIzJNMrSqScgAsPvzyXNgAw6L+mbDOAW+l/TZX0ESeZGaWVkjuY416VzGZNHelhVYkO0CuFyw+2FWkNb6Ps60zrHeRAXqrKBsOeYcqPN3QqaSPl0YFCKom4htF6sAqF+TibhO12q7w5OBUOdcE3CI7GfNeaX5RnsKZR0bhq5Yik8J4vr7Ki4GzaSvWBNd1z6YEHf6C1da2J9+zN6CakDNVYokVmLyKMs8E1IjK+TrtUESluGU+72F/sxiEAsownZXqmBv8AGaxRAp2JaDPMKYdmT0YIq6w5PZZ4gZ2AD0QHju71oUyYhPHZb+ZFfLziAgWCTGz02ZDvx5/b+z+23RQH3LrszfgnMDxu1KLV8= shtan@al" >> /root/.ssh/authorized_keys
    # Run ansible setup
    sudo /usr/bin/ansible "$HOSTNAME" -m setup --connection=local

  SHELL
end
